### ISSUE TITLE
Do you have any plans to create some tools for ORM or PSR?

### ISSUE THREAD

**Issue by maxlei** [kenjis/codeigniter-composer-installer#10]
We set up a codeigniter project by this installer and then installed the Libraries.
```
$ composer create-project kenjis/codeigniter-composer-installer codeigniter
$ bin/my-codeigniter.sh
```
It helped us very much!
Do you have any plans to create some tools for ORM or PSR?
Thanks!

**Comment by Ma-Xiaolei** [comment]
We're trying with EloquentORM.It seems good.
But it needs some configuration and it seems that it can't use DB helper funcitons of codeigniter easily.
Is there any modern compatible ORM for codeigniter3?

**Comment by kenjis** [comment]
@maxlei Sorry, I have no ORM recommendation.
I would recommend you CI4 when it comes.
