### ISSUE TITLE
Third party libraries should be installed under third_party directory?

### ISSUE THREAD

**Issue by ysgk** [kenjis/codeigniter-composer-installer#11]
The `install.php` installs third party libraries under the `application` direcotory. I think, however, they should be placed under `third_party` directory.

Or is this a preferable way for some reason?

Anyway, thanks for this package.

**Comment by kenjis** [comment]
I perhaps made it just to install the libraries with their instructions for installation.
If you could install them into `third_party`, it would be fine.
