### ISSUE TITLE
bin/server.sh crashes after DB access attempt

### ISSUE THREAD

**Issue by judahteng** [kenjis/codeigniter-composer-installer#14]
Hi there, I am running a fresh installation and the bin/server.sh script. I installed Ion Auth 2 and when I try to access localhost:8000/auth, I get a database error, and on second load, I get the following error:

> Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0
Fatal error: Unknown: Failed opening required 'bin/router.php' (include_path='.:') in Unknown on line 0

The terminal looks like this

> [Fri Feb  3 10:38:52 2017] 127.0.0.1:57893 [200]: /auth
[Fri Feb  3 10:39:03 2017] 127.0.0.1:57895 Invalid request (Unexpected EOF)

Every subsequent page load will fail with the same error and I have to restart the server. The exact same page works fine on my local Apache installation, no database error, no EOF error.

**Comment by kenjis** [comment]
I can't reproduce it.

```
$ composer create-project kenjis/codeigniter-composer-installer codeigniter
$ cd codeigniter/
$ php bin/install.php ion-auth 2
$ bin/server.sh
```

And I access `http://localhost:8000/auth`.

I see:
> A Database Error Occurred
> Unable to connect to your database server using the provided settings.
> Filename: core/CodeIgniter.php
> Line Number: 518

Because I have no database.

> [Fri Feb  3 13:03:07 2017] 127.0.0.1:50191 [500]: /auth

**Comment by judahteng** [comment]
It might be my installation then, thanks anyway

**Comment by kenjis** [comment]
No.

**Comment by judahteng** [comment]
Ok thanks.
