### ISSUE TITLE
phpdotenv package integration

### ISSUE THREAD

**Issue by indrakaw** [kenjis/codeigniter-composer-installer#16]
Hello there @kenjis,
This question may out of repo's issue. 

They question: can you integrate [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv) package in CodeIgniter? if yes, how?

This help a lot because sensitive data can be hidden in config.php.

**Comment by kenjis** [comment]
@indrakaw You don't need to use it.
I don't use it, but I don't write sensitive data in config.php.
You can write something like `$_SERVER['DB_PASSWORD']` in your production config.php, and set the environment variable for your web server like Apache.

But if you want to use `.env`, CI4 has a library. <https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Config/DotEnv.php>.

You can use it in CI3 easily:
```php
require '/path/to/DotEnv.php';
$env = new DotEnv('/dir'); // where you have `.env`
$env->load();
unset($env);
```
