### ISSUE TITLE
How to setup Xdebug debugging environment

### ISSUE THREAD

**Issue by MasonFI** [kenjis/codeigniter-composer-installer#27]
I'm having difficulty setting up XDebug debugging environment with this composer style setup. Does anyone have a working setup and could share that? I have the app running in VM, I dont have a glue what to define in Path Mapping.

I have a breaking point in code (I use Eclipse), but it does not have any effect. Xdebug is properly installed.

**Comment by kenjis** [comment]
@MasonFI 

> Xdebug is properly installed.

Did you confirm that Xdebug is enabled on your server?
Did you configure Xdebug properly on your server?

I recommend you check `phpinfo()` output.

And here is my setting:
```
; Enable xdebug extension module
zend_extension=xdebug.so

; see http://xdebug.org/docs/all_settings
xdebug.remote_enable=1
xdebug.remote_host=10.0.2.2

;xdebug.profiler_enable=1
;xdebug.profiler_output_dir=/vagrant/application/logs
```

**Comment by MasonFI** [comment]
Hi,

Ok I got it working now, I just followed these instructions: https://fusionforge.org/plugins/mediawiki/wiki/fusionforge/index.php/Debugging_PHP_over_xdebug_with_Eclipse_and_Vagrant
