### ISSUE TITLE
Updating bin/install.php installed projects?

### ISSUE THREAD

**Issue by enlivenapp** [kenjis/codeigniter-composer-installer#30]
Hi Kenji,

Do you have, or are you planning to create, a script to update the additional projects such as Ion Auth, Matches CLI, etc?

**Comment by kenjis** [comment]
@enlivenapp I have no plan.

**Comment by enlivenapp** [comment]
Ok, thanks.  I did find once I looked a little deeper it will overwrite, but I was more hoping to keep it updated easier.  No worries, I'll get it sorted.   

Thanks for the reply.
