### ISSUE TITLE
PHP information wrong

### ISSUE THREAD

**Issue by bedrijfsportaal** [kenjis/codeigniter-composer-installer#35]
When update with "composer update" the screen shows errors below:

`codeigniter4/framework dev-develop requires php >=7.1 -> your PHP version (7.0.21) does not satisfy that requirement.
codeigniter4/framework dev-develop requires php >=7.1 -> your PHP version (7.0.21) does not satisfy that requirement.
Installation request for codeigniter4/framework dev-develop -> satisfiable by codeigniter4/framework[dev-develop].`

actual PHP version, running with phpinfo(); is 7.1.0 also set in my MAMP, so the actual message is false.

**Comment by kenjis** [comment]
@bedrijfsportaal Would you show me the output of `php -v`?

Eg:
```
$ php -v
PHP 7.2.3 (cli) (built: Mar  8 2018 10:30:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0beta1, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by bedrijfsportaal** [comment]
Hello Kenjis,

Sorry for my late response on this issue, seems to be fixed on my side didn't know what i've done at this point. Think this was just my lak of knowledge on this point normally do not have any problems with your GIT on any webserver.

**Comment by kenjis** [comment]
@bedrijfsportaal MAMP has several versions of PHP. I think you used 7.1 on the Web, but you used 7.0 on your CLI.
