### ISSUE TITLE
Cannot find index.php

### ISSUE THREAD

**Issue by imben1109** [kenjis/codeigniter-composer-installer#39]
I have tried 
```
$ composer create-project kenjis/codeigniter-composer-installer example
```

However, it is found that it is missing index.php in the example folder. If the codeigniter is downloaded from the official page, it would include index.php. 

Thanks.

**Comment by kenjis** [comment]
@imben1109 

It is by design. See <https://github.com/kenjis/codeigniter-composer-installer#folder-structure>.

**Comment by imben1109** [comment]
@kenjis Without index.php, how CodeIngiter operate? Sorry for my silly question.

**Comment by kenjis** [comment]
@imben1109 Not `index.php`, but `public/index.php`.
