### ISSUE TITLE
How to remove "public" from URL using .htaccess? 

### ISSUE THREAD

**Issue by crypsl** [kenjis/codeigniter-composer-installer#40]
I had tried to remove "public" from URL for many times but every time I ran into different problems.
Many of the times, I get loop of "public/public/public..." 
And while installing in subdomain, "public/index.php" can not be removed.

Please I need help on this! Don't want to remove this folder structure just want to make public folder as document root in Apache server. So that "public" doesnot appear in my url.

**Any help will be appreciated?**

**Comment by ProjectOrangeBox** [comment]
This is not something CodeIgniter / PHP handles. This is based on the configuration of your web server. Assuming it is Apache this should explain everything https://stackoverflow.com/questions/5891802/how-do-i-change-the-root-directory-of-an-apache-server
