### ISSUE TITLE
Virtual Host

### ISSUE THREAD

**Issue by ArmandArthur** [kenjis/codeigniter-composer-installer#41]
Hello,

I have a virtual host on directory "public".

But i can't access to parent directory...

And i don't want see in the URL "public".

Could you help me?

**Comment by ProjectOrangeBox** [comment]
Assuming you are using Apache you will need to change your apache configuration file. Apache configuration is what determines where files are served from. In your case you need to specify the public folder.

DMyers

Sent via my iPhone.

**Comment by ArmandArthur** [comment]
Thanks, it 's works.
