### ISSUE TITLE
Extends CI_Controller

### ISSUE THREAD

**Issue by ArmandArthur** [kenjis/codeigniter-composer-installer#42]
Hello,

All Works for me when my controllers extends of CI_Controller.

But when i do : 

`class MY_Commun extends CI_Controller {

AND

class commentaire extends MY_Commun  {`

I have the error following....

Fatal error: Class 'MY_Commun' not found in C:\wamp\www\ci_articles\application\controllers\Commentaire.php

Why my class is not loaded?

When i do : 
Controller_1 extends CI_Controller and
Controller_2 extends CI_Controller , inside controllers folder, it's works !

**Comment by kenjis** [comment]
It is the specification of CodeIgniter 3. CodeIgniter 3 has no real autoloader.
