### ISSUE TITLE
Have named routes

### ISSUE THREAD

**Issue by Ezar101** [kenjis/codeigniter-composer-installer#43]
Hello
First of all, thank you for your remarkable work. 
I've been using your repository under codeigniter 3 for some time now. 
And I'd like to know if you have thought of making one to have named routes and instead of `site_url('controller/method')` make `site_url('route_name')`  ?

**Comment by kenjis** [comment]
This repository is an installer of CI3.
I don't understand why you ask about a function of CI3?

I don't think of making a change to CI3 function.
And I think CI3's `site_url()` API is never changed.
