### ISSUE TITLE
bin/server.sh is not working

### ISSUE THREAD

**Issue by AasSuhendar** [kenjis/codeigniter-composer-installer#9]
I want to run PHP built-in server, but when i write 127.0.0.1:8000 or localhost:8000 is not working.

**Comment by kenjis** [comment]
@AasSuhendar What do you mean by *not working*? What happened? Any error messages?

**Comment by AasSuhendar** [comment]
I run a comand line `bin/server.sh` to run php built-in server, and then i write url `127.0.0.1:8000`, but the web page not appear. The error message in my browser "This Web Page is not avalilable". 
a comand line `bin/server.sh` is equals `php -S localhost:8000` or `127.0.0.1:8000` it is right? Because i had seen in `bin\server.sh` it same way. But, why the web page not appear when i run with your comand line. I'm sorry, I still beginner master. Thanks

**Comment by kenjis** [comment]
@AasSuhendar Did you install CodeIgniter like the following?

~~~
$ composer create-project kenjis/codeigniter-composer-installer codeigniter
~~~

`bin/server.sh` is equals to `php -S 127.0.0.1:8000 -t public/ bin/router.php`.

**Comment by AasSuhendar** [comment]
Yes, follow that way.
I have tried again to install new project but still same condition.
